### PR TITLE
Change Video Morphology dynamically

### PR DESCRIPTION
**Pull request by thisishardik**
Incorporated slider to change morphology of video dynamically.

### CODE REVIEW

**Comment by networkwithoutborders** [comment]
Thanks for you contribution @Aarsh2001 and @thisishardik .  After reviewing your commits, we notice the following:
- [x] Passing slider value dynamically
- [x] Fitting ```imshow(result/frame)``` inside GUI
- [x] Real time object detection    

Here are a few improvisations you can work on:
- [ ] Dilation and erosion methods are carried out twice
- [ ] There is a substantial lag in real time object detection (may be due to point 1)
- [ ] Fitting both the input and output (side by side) inside GUI

**Comment by Aarsh2001** [comment]
Alright , thanks , we'll get on to it then

**Comment by Aarsh2001** [comment]
@Surveillance-NWB can you merge the requests, so that we can work on the suggestions and open another pr for it

**Comment by networkwithoutborders** [comment]
> @Surveillance-NWB can you merge the requests, so that we can work on the suggestions and open another pr for it

PRs will only be merged on the day of evaluation, i.e., 10th August.  All the best!

**Pull request closed without merging**
